name: Build Before Merge in Master With Tests

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Pull Request
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Execute Tests (Unit + Integration)
        run: mvn clean verify -Dspring.profiles.active=test --file pom.xml --no-transfer-progress
      - name: Bump version in pom.xml
        if: success()
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//')
          MAJOR=$(echo $BASE_VERSION | cut -d. -f1)
          MINOR=$(echo $BASE_VERSION | cut -d. -f2)
          PATCH=$(echo $BASE_VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH-SNAPSHOT"
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn versions:commit
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
      - name: Commit and Push Changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout ${{ github.head_ref }}
          git add pom.xml
          git commit -m "Bump version to $NEW_VERSION"
          git push origin ${{ github.head_ref }}